Repository boostcampwm-2024/web18-inear, pull requests merged in 2024-11, with the labels that each got.

#4 Redis 연동
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/common/common.module.ts
  server/src/common/redis/redis.module.ts
  server/src/common/redis/redis.provider.ts
  yarn.lock
Labels: 🎲 BE, 🌲 setting

#5 tailwind 설정, 사이드바 구현
  client/index.html
  client/package.json
  client/postcss.config.js
  client/src/App.css
  client/src/App.tsx
  client/src/assets/github-logo.png
  client/src/assets/sidebar-event.png
  client/src/entities/streamingListItem/StreamingListItem.tsx
  client/src/entities/streamingListItem/index.ts
  client/src/index.css
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/index.ts
  client/src/reset.css
  client/src/shared/icons/InearLogo.tsx
  client/src/shared/icons/inex.ts
  client/src/widgets/sidebar/Credit.tsx
  client/src/widgets/sidebar/Sidebar.tsx
  client/src/widgets/sidebar/StreamingList.css
  client/src/widgets/sidebar/StreamingList.tsx
  client/src/widgets/sidebar/index.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: ✨ FE, 🚀 feature, 🌲 setting

#6 Room 관련 레디스 설계 및 RoomRepository 구현
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/common/redis/redis.provider.ts
  server/src/room/room.module.ts
  server/src/room/room.repository.ts
  server/tsconfig.json
  yarn.lock
Labels: 🎲 BE, 🚀 feature

#7 [BE] 사용자 식별 값 및 랜덤 이름 반환
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/common/randomname/random-name.util.ts
  server/src/room/room.controller.ts
  server/src/room/room.module.ts
  server/src/room/room.repository.ts
Labels: 🎲 BE, 🚀 feature

#12 msw 세팅
  client/package.json
  client/public/mockServiceWorker.js
  client/src/entities/streamingListItem/StreamingListItem.tsx
  client/src/main.tsx
  client/src/mocks/browser.ts
  client/src/mocks/handlers.ts
  client/src/mocks/model/rooms.json
  client/src/widgets/sidebar/StreamingList.tsx
  yarn.lock
Labels: ✨ FE, 🚀 feature, 🌲 setting

#16 FSD 디렉토리 정리 및 메인 페이지 구현
  client/package.json
  client/src/assets/logo-album-cover.png
  client/src/assets/main-event.png
  client/src/entities/streamingListItem/index.ts
  client/src/index.css
  client/src/pages/MainPage/MainPage.tsx
  client/src/widgets/albums/AlbumCard.tsx
  client/src/widgets/albums/AlbumList.tsx
  client/src/widgets/albums/index.ts
  client/src/widgets/sidebar/Credit.tsx
  client/src/widgets/sidebar/StreamingList.tsx
  client/src/widgets/sidebar/StreamingListItem.tsx
Labels: ✨ FE, 🚀 feature

#19 Docker 연동
  client/Dockerfile
  docker-compose.yml
  server/Dockerfile
Labels: 🎲 BE, 🌲 setting

#26 도커 compose 수정 및 Blue/Green 무중단 배포 스크립트 작성
  .github/workflows/scripts/deploy.sh
  docker-compose.blue.yml
  docker-compose.green.yml
  docker-compose.yml
Labels: 🎲 BE, 🚀 feature

#29 ci: github actions CI 스크립트 작성
  .github/workflows/docker-image.yml
Labels: 🎲 BE, 🌲 setting

#30 nginx 설정 및 docker 연동 위한 셋업
  nginx/Dockerfile
  nginx/conf.d/default.conf
  nginx/nginx.conf
Labels: 🎲 BE, 🌲 setting

#31 한 번의 PR Merge에 GitHub Action이 두 번 발생하는 문제 해결
  .github/workflows/docker-image.yml
Labels: 👽 bug, 🎲 BE, 🌲 setting

#38 소켓 사용해서 방 생성 / 입장
  server/package.json
  server/public/socket-test.html
  server/src/app.module.ts
  server/src/common/randomname/random-name.util.ts
  server/src/main.ts
  server/src/room/room.controller.ts
  server/src/room/room.entity.ts
  server/src/room/room.gateway.spec.ts
  server/src/room/room.gateway.ts
  server/src/room/room.repository.ts
  yarn.lock
Labels: 🎲 BE, 🚀 feature

#39 스트리밍 페이지 레이아웃 구현
  client/.storybook/preview.ts
  client/src/assets/sample-album-cover-1.png
  client/src/assets/sample-album-cover-2.png
  client/src/assets/sample-album-cover-3.png
  client/src/entities/album/type.ts
  client/src/features/chatting/ChatInput.tsx
  client/src/pages/StreamingPage/StreamingPage.tsx
  client/src/widgets/albums/AlbumCard.tsx
  client/src/widgets/albums/AlbumList.tsx
  client/src/widgets/chatting/Chatting.tsx
  client/src/widgets/chatting/Message.stories.tsx
  client/src/widgets/chatting/Message.tsx
  client/src/widgets/chatting/index.ts
  client/src/widgets/streaming/AlbumBackground.tsx
  client/src/widgets/streaming/AlbumInfo.tsx
  client/src/widgets/streaming/Streaming.tsx
  client/src/widgets/streaming/index.ts
  client/src/widgets/vote/Vote.tsx
Labels: ✨ FE, 🎨 design, 🚀 feature

#41 RoomGateway에서 사용자 방 퇴장에 관한 구현
  server/public/socket-test.html
  server/src/room/room.gateway.ts
  server/src/room/room.repository.ts
Labels: 🎲 BE, 🚀 feature

#24 docs: 이슈 템플릿 생성 - 구현/문제 해결
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/ISSUE_TEMPLATE/문제-사항-보고.md
Labels: 📚 documentation

#46 fix: 랜덤 동물 이름 생성 시 undeined가 생기지 않도록 개선
  server/src/common/randomname/random-name.util.ts
Labels: 👽 bug, 🎲 BE

#47 [BE] 채팅 브로드 캐스팅 구현
  server/public/socket-test.html
  server/src/room/room.gateway.ts
Labels: 🎲 BE, 🚀 feature

#50 라우터 설정
  client/package.json
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/StreamingPage/StreamingPage.tsx
  client/src/pages/index.tsx
  client/src/shared/icons/ChevronDown.tsx
  client/src/widgets/chatting/Chatting.tsx
  client/src/widgets/streaming/AlbumInfo.tsx
  client/src/widgets/streaming/Playlist.tsx
  client/src/widgets/streaming/PlaylistMock.ts
  client/src/widgets/streaming/Streaming.tsx
  package.json
  yarn.lock
Labels: ✨ FE, 🚀 feature

#49 [BE] 입/퇴장 시 카운트 이벤트 적용 및 퇴장 오류 수정
  server/public/socket-test.html
  server/src/room/room.entity.ts
  server/src/room/room.gateway.ts
  server/src/room/room.repository.ts
Labels: 👽 bug, 🎲 BE, 🚀 feature

#57 채팅 기능 구현
  client/index.html
  client/public/favicon.ico
  client/src/Layout.tsx
  client/src/entities/album/types.ts
  client/src/entities/message/types.ts
  client/src/entities/room/types.ts
  client/src/features/chatting/ChatInput.tsx
  client/src/main.tsx
  client/src/pages/ManagePage/ManagePage.tsx
  client/src/pages/ManagePage/index.ts
  client/src/pages/Router.tsx
  client/src/pages/StreamingPage/StreamingPage.tsx
  client/src/pages/StreamingPage/useSocketEvents.ts
  client/src/pages/StreamingPage/useStreamingRoom.ts
  client/src/pages/index.tsx
  client/src/socket.ts
  client/src/widgets/chatting/Chatting.css
  client/src/widgets/chatting/Chatting.tsx
  client/src/widgets/chatting/ChattingContainer.tsx
  client/src/widgets/chatting/Message.tsx
  client/src/widgets/chatting/MessageList.tsx
  client/src/widgets/chatting/index.ts
  client/src/widgets/chatting/useChatMessage.ts
  client/src/widgets/sidebar/StreamingList.tsx
  client/src/widgets/sidebar/StreamingListItem.tsx
  client/src/widgets/streaming/AlbumInfo.tsx
  client/src/widgets/streaming/Streaming.tsx
  server/public/socket-test.html
  yarn.lock
Labels: ✨ FE, 🚀 feature

#58 [BE] 로컬 디렉토리에 있는 mp3 파일에 관한 변환 작업을 진행
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/src/music/music.module.ts
  server/src/music/music.processor.ts
  yarn.lock
Labels: 🎲 BE, 🚀 feature

#60 fix: 통신 방식 수정
  client/src/socket.ts
Labels: 👽 bug

#63 디렉토리 소유자 설정
  .github/CODEOWNERS
Labels: 🌲 setting

#62 가사 컴포넌트 구현
  client/src/shared/styles/Scrollbar.css
  client/src/widgets/chatting/Chatting.css
  client/src/widgets/chatting/MessageList.tsx
  client/src/widgets/sidebar/StreamingList.css
  client/src/widgets/sidebar/StreamingList.tsx
  client/src/widgets/streaming/AlbumInfo.tsx
  client/src/widgets/streaming/LyricsPanel.css
  yarn.lock
Labels: ✨ FE, 🎨 design, 🚀 feature

#65 채팅 기능 리팩토링 및 소켓 URL 수정
  client/src/app/router/Router.tsx
  client/src/app/router/config.ts
  client/src/app/router/index.ts
  client/src/app/router/routes.tsx
  client/src/features/chatting/index.ts
  client/src/features/chatting/model/sendMessage.ts
  client/src/features/chatting/ui/ChatInput.tsx
  client/src/main.tsx
  client/src/pages/AlbumPage/index.ts
  client/src/pages/AlbumPage/ui/AlbumPage.tsx
  client/src/pages/ManagePage/ManagePage.tsx
  client/src/pages/Router.tsx
  client/src/pages/StreamingPage/useStreamingRoom.ts
  client/src/shared/api/socket.ts
  client/src/shared/icon/ChevronDown.tsx
  client/src/shared/icon/InearLogo.tsx
  client/src/shared/icon/SendIcon.tsx
  client/src/shared/icon/inex.ts
  client/src/shared/styles/Scrollbar.css
  client/src/widgets/chatting/ChattingContainer.tsx
  client/src/widgets/chatting/useChatMessage.ts
  client/src/widgets/sidebar/Sidebar.tsx
  client/src/widgets/streaming/AlbumInfo.tsx
  client/src/widgets/vote/Vote.tsx
Labels: ✨ FE

#66 cd 방식 변경
  .github/workflows/docker-image.yml
  docker-compose-green.yml
  docker-compose.yml
  nginx/Dockerfile
  nginx/conf.d/default.conf
  server/src/app.controller.ts
  server/src/main.ts
Labels: 🌲 setting

#71 HLS 프로토콜로 음악 스트리밍 기능 구현
  server/package.json
  server/src/music/music.controller.ts
  server/src/music/music.module.ts
  server/src/music/music.repository.ts
  server/src/music/music.service.ts
  server/src/music/parser/m3u8-parser.ts
  yarn.lock
Labels: 🎲 BE, 🚀 feature

#76 로컬 환경 개발전용 docker 환경 구성
  client/Dockerfile
  docker-compose.yml
  nginx/Dockerfile
  nginx/conf.d/default.conf
  server/Dockerfile
  server/tsconfig.json
Labels: 👽 bug, 🎲 BE, 🌲 setting

#77 관리자가 업로드한 음악 파일 m3u8로 형식 파싱하고 Object storage에 업로드, 이미지 Object storage에 업로드
  docker-compose.yml
  nginx/Dockerfile
  nginx/conf.d/default.conf
  server/Dockerfile
  server/package.json
  server/src/admin/admin.controller.ts
  server/src/admin/admin.module.ts
  server/src/admin/admin.service.ts
  server/src/admin/dto/AlbumDto.ts
  server/src/admin/dto/SongDto.ts
  server/src/album/album.service.ts
  server/src/app.module.ts
  server/src/main.ts
  server/src/music/music.processor.ts
  server/src/room/room.gateway.ts
  yarn.lock
Labels: 🎲 BE, 🚀 feature

#75 s3로부터 이미지 URL 반환하는 기능 추가
  server/src/app.module.ts
  server/src/emoji/emoji-request-dto.ts
  server/src/emoji/emoji.controller.ts
  server/src/emoji/emoji.module.ts
  server/src/emoji/emoji.service.ts
  server/src/main.ts
Labels: 🎲 BE, 🚀 feature

#70 관리자 페이지 레이아웃 구현
  client/src/Layout.tsx
  client/src/app/router/routes.tsx
  client/src/entities/album/types.ts
  client/src/features/albumRegister/index.ts
  client/src/features/albumRegister/model/types.ts
  client/src/features/albumRegister/model/useAlbumForm.ts
  client/src/features/albumRegister/model/useAlbumRegister.ts
  client/src/features/albumRegister/ui/AlbumForm.tsx
  client/src/features/albumRegister/ui/SongForm.tsx
  client/src/pages/AdminPage/index.ts
  client/src/pages/AdminPage/ui/AdminPage.tsx
  client/src/pages/MainPage/index.ts
  client/src/pages/MainPage/ui/MainPage.tsx
  client/src/pages/ManagePage/ManagePage.tsx
  client/src/pages/ManagePage/index.ts
  client/src/pages/StreamingPage/index.ts
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/hook/useSocketEvents.ts
  client/src/shared/hook/useStreamingRoom.ts
  client/src/shared/ui/Button.tsx
  client/src/shared/ui/Input.tsx
  client/src/shared/ui/index.ts
  client/src/widgets/albums/index.ts
  client/src/widgets/albums/ui/AlbumCard.tsx
  client/src/widgets/albums/ui/AlbumList.tsx
  client/src/widgets/chatting/Message.stories.tsx
  client/src/widgets/chatting/index.ts
  client/src/widgets/chatting/ui/Chatting.css
  client/src/widgets/chatting/ui/ChattingContainer.tsx
  client/src/widgets/chatting/ui/Message.tsx
  client/src/widgets/chatting/ui/MessageList.tsx
  client/src/widgets/sidebar/index.ts
  client/src/widgets/sidebar/ui/Credit.tsx
  client/src/widgets/sidebar/ui/Sidebar.tsx
  client/src/widgets/sidebar/ui/StreamingList.css
  client/src/widgets/sidebar/ui/StreamingList.tsx
  client/src/widgets/sidebar/ui/StreamingListItem.tsx
  client/src/widgets/streaming/Playlist.tsx
  client/src/widgets/streaming/PlaylistMock.ts
  client/src/widgets/streaming/index.ts
  client/src/widgets/streaming/ui/AlbumBackground.tsx
  client/src/widgets/streaming/ui/AlbumInfo.tsx
  client/src/widgets/streaming/ui/LyricsPanel.css
  client/src/widgets/streaming/ui/Streaming.tsx
  client/src/widgets/vote/index.ts
  client/src/widgets/vote/ui/Vote.tsx
Labels: ✨ FE, 🚀 feature

#84 관리자 페이지 서버 통신
  client/package.json
  client/src/features/albumRegister/index.ts
  client/src/features/albumRegister/model/types.ts
  client/src/features/albumRegister/model/useAlbumForm.ts
  client/src/features/albumRegister/model/useAlbumRegister.ts
  client/src/features/albumRegister/ui/AlbumForm.tsx
  client/src/pages/AdminPage/ui/AdminPage.tsx
  yarn.lock
Labels: ✨ FE, 🚀 feature

#82 음악 스트리밍 사용자 입장 시간 계산 로직 수정
  server/src/main.ts
  server/src/music/music.controller.ts
  server/src/music/music.repository.ts
  server/src/music/music.service.ts
  server/src/music/parser/m3u8-parser.ts
Labels: 👽 bug, 🎲 BE, 🚀 feature

#85 앨범 및 노래 정보를 기반으로 레디스에 형식에 맞게 데이터를 저장한다
  server/src/admin/admin.controller.ts
  server/src/admin/admin.module.ts
  server/src/admin/admin.redis.repository.ts
  server/src/admin/dto/AlbumDto.ts
  server/src/admin/dto/SongDto.ts
  server/src/music/music.processor.ts
  tsconfig.json
  yarn.lock
Labels: 🎲 BE, 🚀 feature

#86 앨범 및 음악 저장을 위한 mysql 연동
  server/package.json
  server/src/admin/admin.controller.ts
  server/src/admin/admin.module.ts
  server/src/admin/dto/AlbumDto.ts
  server/src/admin/dto/SongDto.ts
  server/src/album/album.entity.ts
  server/src/album/album.module.ts
  server/src/app.module.ts
  server/src/song/song.entity.ts
  server/src/song/song.module.ts
  server/src/song/songSave.dto.ts
  yarn.lock
Labels: 🎲 BE, 🚀 feature

#87 스트리밍 클라이언트 연결
  client/index.html
  client/package.json
  client/src/app/router/routes.tsx
  client/src/pages/AdminPage/ui/AdminPage.tsx
  client/src/pages/HlsTestPage/index.ts
  client/src/pages/HlsTestPage/ui/HlsTestPage.tsx
  client/src/pages/StreamingErrorPage/index.ts
  client/src/pages/StreamingErrorPage/ui/StreamingErrorPage.tsx
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/hook/useStreamingRoom.ts
  client/src/shared/icon/PlayIcon.tsx
  client/src/shared/icon/inex.ts
  client/src/widgets/chatting/ui/MessageList.tsx
  client/src/widgets/sidebar/ui/StreamingList.tsx
  client/src/widgets/streaming/ui/AlbumInfo.tsx
  client/src/widgets/streaming/ui/AudioController.tsx
  server/public/hls-test.html
  yarn.lock
Labels: ✨ FE, 🚀 feature

#88 스트리밍 페이지 접근 시 관련 데이터를 반환하는 API 구현
  server/src/album/album.entity.ts
  server/src/album/albumResponse.dto.ts
  server/src/app.module.ts
  server/src/room/room.controller.ts
  server/src/room/room.gateway.ts
  server/src/song/song.entity.ts
  server/src/song/songResponse.dto.ts
Labels: 🎲 BE, 🚀 feature

#91 HLS 코드 리팩토링
  server/src/common/s3Cache/s3Cache.service.ts
  server/src/music/music.module.ts
  server/src/music/music.service.ts
Labels: 🎲 BE, 🎵 Refactor

#95 방 생성 로직 및 레이어 개선
  server/src/admin/admin.controller.ts
  server/src/admin/admin.module.ts
  server/src/admin/admin.service.ts
  server/src/album/album.module.ts
  server/src/album/album.repository.ts
  server/src/app.module.ts
  server/src/common/constants/repository.constant.ts
  server/src/music/music.module.ts
  server/src/room/room.constant.ts
  server/src/room/room.controller.ts
  server/src/room/room.entity.ts
  server/src/room/room.gateway.ts
  server/src/room/room.module.ts
  server/src/room/room.repository.ts
  server/src/room/room.service.ts
  server/src/song/song.module.ts
  server/src/song/song.repository.ts
Labels: 🎲 BE, 🎵 Refactor

#97 스트리밍 페이지 HLS 관련 코드 리팩토링
  client/index.html
  client/src/app/router/routes.tsx
  client/src/entities/album/types.ts
  client/src/entities/songDetail/index.ts
  client/src/entities/songDetail/ui/LyricsPanel.css
  client/src/entities/songDetail/ui/LyricsPanel.tsx
  client/src/entities/songDetail/ui/PlaylistPanel.tsx
  client/src/features/albumStreaming/index.ts
  client/src/features/albumStreaming/lib/constants.ts
  client/src/features/albumStreaming/lib/useStreamingPlayer.ts
  client/src/features/albumStreaming/model/types.ts
  client/src/features/songDetail/index.ts
  client/src/features/songDetail/model/types.ts
  client/src/features/songDetail/ui/CategoryButton.tsx
  client/src/features/songDetail/ui/SongDetail.tsx
  client/src/features/songDetail/ui/SongDetailContent.tsx
  client/src/features/songDetail/ui/SongDetailHeader.tsx
  client/src/mocks/browser.ts
  client/src/mocks/handlers.ts
  client/src/mocks/model/rooms.json
  client/src/pages/HlsTestPage/index.ts
  client/src/pages/HlsTestPage/ui/HlsTestPage.tsx
  client/src/shared/hook/useStreamingRoom.ts
  client/src/widgets/streaming/ui/AlbumInfo.tsx
  client/src/widgets/streaming/ui/Streaming.tsx
Labels: ✨ FE, 🎵 Refactor

#104 음악 release date 타입 수정
  server/src/admin/admin.controller.ts
  server/src/admin/admin.service.ts
  server/src/admin/dto/AlbumDto.ts
  server/src/album/album.entity.ts
  server/src/album/albumResponse.dto.ts
Labels: 👽 bug, 🎲 BE, 🎵 Refactor

#102 [FE] 어드민 로그인 페이지 만들기
  client/.gitignore
  client/src/app/router/routes.tsx
  client/src/pages/AdminLoginPage/index.ts
  client/src/pages/AdminLoginPage/ui/AdminLoginPage.tsx
  server/.gitignore
Labels: ✨ FE, 🚀 feature

#116 플레이리스트 데이터 연결 및 방 입장 소켓 로직 변경
  client/package.json
  client/src/entities/album/types.ts
  client/src/entities/songDetail/ui/LyricsPanel.tsx
  client/src/entities/songDetail/ui/PlaylistPanel.css
  client/src/entities/songDetail/ui/PlaylistPanel.tsx
  client/src/entities/songDetail/ui/PlaylistPanelCredit.tsx
  client/src/entities/songDetail/ui/PlaylistPanelSong.tsx
  client/src/features/albumStreaming/lib/useStreamingPlayer.ts
  client/src/features/chatting/model/sendMessage.ts
  client/src/features/chatting/ui/ChatInput.tsx
  client/src/features/songDetail/ui/SongDetail.tsx
  client/src/features/songDetail/ui/SongDetailContent.tsx
  client/src/pages/AdminPage/ui/AdminPage.tsx
  client/src/pages/MainPage/ui/MainPage.tsx
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/api/socket.ts
  client/src/shared/hook/useSocketEvents.ts
  client/src/shared/hook/useStreamingRoom.ts
  client/src/shared/lottie/music.json
  client/src/shared/store/useChatMessageStore.ts
  client/src/shared/store/useSocketStore.ts
  client/src/widgets/chatting/useChatMessage.ts
  client/src/widgets/streaming/ui/AlbumInfo.tsx
  client/src/widgets/streaming/ui/AudioController.tsx
  client/src/widgets/streaming/ui/Streaming.tsx
  server/public/socket-test.html
  yarn.lock
Labels: ✨ FE, 🚀 feature

#110 [FE] 관리자 페이지 접근 시도시 ProtectedRoutes를 통하여 리다이렉션 진행
  client/src/app/router/routes.tsx
  client/src/components/ProtectedRoute.tsx
  client/src/features/albumRegister/model/useAlbumForm.ts
  client/src/pages/AdminLoginPage/ui/AdminLoginPage.tsx
  client/src/shared/api/axios.ts
Labels: ✨ FE, 🚀 feature

#111 서버 전역 예외 처리
  server/src/admin/admin.controller.ts
  server/src/admin/admin.service.ts
  server/src/app.controller.ts
  server/src/common/exceptions/base.exception.ts
  server/src/common/exceptions/domain/room/room-inactive.exception.ts
  server/src/common/exceptions/domain/room/room-is-full.exception.ts
  server/src/common/exceptions/domain/room/room-not-found.exception.ts
  server/src/common/exceptions/domain/room/user-not-in-room.exception.ts
  server/src/common/exceptions/domain/song/missing-song-files.exception.ts
  server/src/common/exceptions/global-exception.filter.ts
  server/src/main.ts
  server/src/room/room.controller.ts
  server/src/room/room.gateway.ts
  server/src/room/room.repository.ts
Labels: 🎲 BE, 🌲 setting

#117 로컬 스토리지에서 쿠키로 로그인 로직 변경
  .gitignore
  client/src/components/ProtectedRoute.tsx
  client/src/pages/AdminLoginPage/ui/AdminLoginPage.tsx
  client/src/shared/api/axios.ts
  server/package.json
  server/src/admin/admin.controller.ts
  server/src/admin/admin.guard.ts
  server/src/admin/admin.service.ts
  server/src/main.ts
  yarn.lock
Labels: ✨ FE, 🎲 BE, 🎵 Refactor

#119 앨범 생성 시, 트랜잭션 구현
  server/src/admin/admin.controller.ts
  server/src/admin/admin.module.ts
  server/src/admin/admin.transaction.service.ts
  server/src/album/album.repository.ts
  server/src/common/exceptions/domain/album/album-creation-fail.exception.ts
Labels: 🎲 BE, 🚀 feature

#123 메인페이지 서버 데이터 연결
  client/package.json
  client/public/mockServiceWorker.js
  client/src/entities/album/types.ts
  client/src/entities/room/types.ts
  client/src/features/albumRegister/model/useAlbumForm.ts
  client/src/features/albumStreaming/lib/useStreamingPlayer.ts
  client/src/pages/MainPage/ui/MainPage.tsx
  client/src/shared/api/adminAPI.ts
  client/src/shared/api/errorMessage.ts
  client/src/shared/api/publicAPI.ts
  client/src/shared/hook/useSocketEvents.ts
  client/src/shared/hook/useStreamingRoom.ts
  client/src/widgets/banner/index.ts
  client/src/widgets/banner/ui/Banner.css
  client/src/widgets/banner/ui/Banner.tsx
  client/src/widgets/banner/ui/BannerSlide.tsx
  client/src/widgets/chatting/ui/Message.tsx
  client/src/widgets/sidebar/ui/RoomList.tsx
  client/src/widgets/sidebar/ui/RoomListItem.tsx
  client/src/widgets/sidebar/ui/Sidebar.tsx
  client/src/widgets/sidebar/ui/StreamingList.tsx
  client/src/widgets/sidebar/ui/StreamingListItem.tsx
  yarn.lock
Labels: ✨ FE, 🎨 design, 🚀 feature

#124 joinTimestamp 삭제
  client/src/features/albumStreaming/lib/useStreamingPlayer.ts
  server/src/music/music.controller.ts
  server/src/music/music.service.ts
Labels: 👽 bug, 🎲 BE

#122 최근 등록 앨범 가져오는 API 추가
  server/src/album/album.controller.ts
  server/src/album/album.repository.ts
  server/src/album/album.service.ts
  server/src/album/dto/ended-album-response.dto.ts
Labels: 🎲 BE, 🚀 feature

#125 gateway에서 발생하는 예외 처리
  server/src/common/exceptions/ws-exception.filter.ts
  server/src/room/room.gateway.ts
Labels: 🎲 BE, 🌲 setting

#134 스케쥴러 기반으로 테스트 앨범을 주기적으로 다시 메인 페이지에 업데이트
  server/package.json
  server/src/album/album.repository.ts
  server/src/app.module.ts
  server/src/common/scheduler/scheduler.service.ts
  yarn.lock
Labels: 🥔 test

#137 최근 등록한 앨범 데이터 연동
  client/src/entities/room/types.ts
  client/src/shared/api/publicAPI.ts
  client/src/widgets/albums/ui/AlbumCard.tsx
  client/src/widgets/albums/ui/AlbumList.tsx
  server/src/album/album.repository.ts
  server/src/album/dto/ended-album-response.dto.ts
Labels: ✨ FE, 🚀 feature

#138 음악 플레이리스트 다음으로 넘어가도록 구현
  client/src/features/albumStreaming/lib/useStreamingPlayer.ts
  client/src/pages/MainPage/ui/MainPage.tsx
  client/src/shared/api/publicAPI.ts
  client/src/shared/store/useSocketStore.ts
  client/src/widgets/streaming/ui/AlbumInfo.tsx
  client/src/widgets/streaming/ui/Streaming.tsx
Labels: ✨ FE, 🚀 feature

#139 [FE] 스트리밍 방사용자 명수 업데이트
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/store/useSocketStore.ts
Labels: ✨ FE, 🚀 feature

#143 앨범 상세 API 구현
  server/src/album/album.controller.ts
  server/src/album/album.repository.ts
  server/src/album/album.service.ts
  server/src/album/dto/album-detail-response.dto.ts
  server/src/album/dto/ended-album-response.dto.ts
  server/src/album/dto/main-banner-response.dto.ts
  server/src/album/dto/side-bar-response.dto.ts
Labels: 🎲 BE, 🚀 feature

#145 스트리밍 페이지 볼륨 조절
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/icon/Volume.tsx
  client/src/shared/icon/inex.ts
  client/src/widgets/chatting/Message.stories.tsx
  client/src/widgets/streaming/ui/AlbumInfo.tsx
  client/src/widgets/streaming/ui/Streaming.tsx
  client/src/widgets/streaming/ui/Volume.css
Labels: ✨ FE, 🚀 feature

#148 사용자 투표 시 실시간 투표 현황 업데이트 및 렌더링
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/store/useVoteStore.ts
  client/src/widgets/vote/ui/ScrollBar.css
  client/src/widgets/vote/ui/Vote.tsx
  client/src/widgets/vote/useVote.ts
  server/src/room/room.gateway.ts
  server/src/room/room.repository.ts
  server/src/room/room.service.ts
Labels: ✨ FE, 🎲 BE, 🚀 feature

#153 앨범 데이터 변경 오류 수정
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/icon/Person.tsx
Labels: 👽 bug, ✨ FE

#154 메인 페이지 리팩토링
  client/src/widgets/albums/ui/AlbumList.tsx
  client/src/widgets/banner/types/index.ts
  client/src/widgets/banner/ui/BannerSlide.tsx
Labels: ✨ FE, 🎵 Refactor

#147 [Test] 관리자 앨범 및 파일 업로드 후 디비 저장에 관한 동작 테스트 진행
  package.json
  server/.gitignore
  server/package.json
  server/src/admin/admin.service.ts
  server/src/app.controller.spec.ts
  server/src/music/music.processor.ts
  server/src/room/room.gateway.spec.ts
  server/test/admin.integration.spec.ts
  server/test/app.e2e-spec.ts
  server/test/config/typeorm.config.ts
  server/test/jest-e2e.json
  server/test/mock/album.mock.ts
  server/tsconfig.json
  yarn.lock
Labels: 🎲 BE, 🥔 test

#156 hls error 수정
  client/src/features/albumStreaming/lib/useStreamingPlayer.ts
Labels: 👽 bug, ✨ FE

#157 식별자가 동일한 이슈 해결
  server/src/room/room.gateway.ts
  server/src/room/room.service.ts
Labels: 👽 bug, 🎲 BE

#158 앨범 발매 시간 자동 업데이트 스케쥴러에서 로컬 레디스에도 반영되게 변경
  server/src/album/album.repository.ts
  server/src/common/scheduler/scheduler.service.ts
Labels: 🎵 Refactor

#161 앨범 관련 커스텀 에러 처리
  server/src/common/exceptions/domain/album/album-not-found-by-timestamp.exception.ts
  server/src/common/exceptions/domain/album/album-not-found.exception.ts
  server/src/music/music.repository.ts
Labels: 👽 bug, 🎲 BE

#162 broadcast 이벤트 발생 시 사용자 id를 받아 출력하도록 수정
  client/src/entities/message/types.ts
  client/src/widgets/chatting/ui/Message.tsx
  client/src/widgets/chatting/ui/MessageList.tsx
Labels: ✨ FE, 🚀 feature

#165 투표 이벤트와 투표 조회 이벤트 분리
  client/src/shared/store/useVoteStore.ts
  client/src/widgets/vote/useVote.ts
  server/src/room/room.gateway.ts
  server/src/room/room.service.ts
Labels: 👽 bug, ✨ FE, 🎲 BE

#146 앨범 상세 코멘트 API
  server/src/app.module.ts
  server/src/comment/comment.controller.ts
  server/src/comment/comment.entity.ts
  server/src/comment/comment.module.ts
  server/src/comment/comment.repository.ts
  server/src/comment/comment.service.ts
  server/src/comment/dto/album-comment-response.dto.ts
Labels: 🎲 BE, 🚀 feature
