Repository boostcampwm-2024/web18-inear, pull requests merged in 2024-12, with the labels that each got.

#169 메인 페이지의 앨범 세션 응답값 개선
  server/src/album/album.repository.ts
Labels: 🎲 BE, 🚀 feature

#171 볼륨 동작 개선
  client/src/shared/icon/VolumeMuted.tsx
  client/src/shared/icon/inex.ts
  client/src/widgets/streaming/ui/AlbumInfo.tsx
Labels: ✨ FE, 🚀 feature, 🎵 Refactor

#186 볼륨 음소거 버튼 실행 조건 수정 및 mouse 이벤트 조건 수정
  client/src/widgets/streaming/ui/AlbumInfo.tsx
Labels: 👽 bug, ✨ FE

#187 대기화면 구현
  client/package.json
  client/src/GlobalBoundary.tsx
  client/src/Layout.tsx
  client/src/NetworkBoundary.tsx
  client/src/entities/album/types.ts
  client/src/features/albumStreaming/lib/useStreamingPlayer.ts
  client/src/main.tsx
  client/src/pages/MainPage/ui/MainPage.tsx
  client/src/pages/StreamingPage/ui/Standby.tsx
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/api/publicAPI.ts
  client/src/shared/api/socket.ts
  client/src/shared/ui/Timer.tsx
  client/src/shared/ui/index.ts
  client/src/shared/util/timeUtils.ts
  client/src/widgets/banner/types/index.ts
  client/src/widgets/banner/ui/BannerSlide.tsx
  client/src/widgets/sidebar/hook/useSidebarAlbum.ts
  client/src/widgets/sidebar/ui/Credit.tsx
  client/src/widgets/sidebar/ui/Sidebar.tsx
  client/src/widgets/vote/ui/Vote.tsx
  server/src/music/music.repository.ts
  server/src/room/room.service.ts
  yarn.lock
Labels: ✨ FE, 🚀 feature

#200 기본 배너 추가
  client/src/entities/albumRegister/types.ts
  client/src/features/albumRegister/model/useAlbumForm.ts
  client/src/features/albumRegister/ui/AlbumForm.tsx
  client/src/features/albumRegister/ui/SongForm.tsx
  client/src/features/albumStreaming/hook/constants.ts
  client/src/features/albumStreaming/hook/useStreamingPlayer.ts
  client/src/features/chatting/ui/ChatInput.tsx
  client/src/features/chattingInput/index.ts
  client/src/features/chattingInput/model/sendMessage.ts
  client/src/features/chattingInput/ui/ChatInput.tsx
  client/src/pages/StreamingPage/ui/Notice.tsx
  client/src/pages/StreamingPage/ui/Standby.tsx
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/shared/store/useChatMessageStore.ts
  client/src/widgets/chatting/hook/useChatMessage.ts
  client/src/widgets/chatting/ui/ChattingContainer.tsx
  client/src/widgets/streaming/ui/AlbumInfo.tsx
Labels: 👽 bug, ✨ FE

#199 소켓 부하 테스트
  server/package.json
  server/socket-test.yml
  server/src/common/randomname/random-name.util.ts
  yarn.lock
Labels: 🎲 BE, 🥔 test

#198 앨범 상세 페이지 구현
  client/package.json
  client/src/App.tsx
  client/src/app/router/routes.tsx
  client/src/pages/AlbumPage/ui/AlbumPage.tsx
  client/src/shared/api/errorMessage.ts
  client/src/shared/api/publicAPI.ts
  client/src/widgets/albums/index.ts
  client/src/widgets/albums/ui/AlbumArtist.tsx
  client/src/widgets/albums/ui/AlbumList.tsx
  client/src/widgets/albums/ui/Comment.tsx
  client/src/widgets/albums/ui/CommentList.tsx
  client/src/widgets/albums/ui/Playlist.tsx
  client/src/widgets/albums/ui/Scrollbar.css
  client/src/widgets/albums/ui/TrackItem.tsx
  server/src/comment/comment.repository.ts
  server/src/comment/dto/album-comment-response.dto.ts
  yarn.lock
Labels: ✨ FE, 🎲 BE, 🚀 feature, 🎵 Refactor

#201 백엔드 도커 이미지 경량화
  server/Dockerfile
Labels: 🎲 BE, 🌲 setting

#204 앨범 정보 안바뀌는 오류 수정
  client/src/App.tsx
  client/src/app/router/ProtectedRoute.tsx
  client/src/app/router/routes.tsx
  client/src/features/albumStreaming/hook/useStreamingPlayer.ts
  client/src/features/useCounter/index.ts
  client/src/features/useCounter/ui/UserCounter.tsx
  client/src/pages/StreamingPage/ui/StreamingPage.tsx
  client/src/widgets/chatting/ui/Chatting.tsx
  client/src/widgets/streaming/ui/AlbumInfo.tsx
  client/src/widgets/streaming/ui/AudioController.tsx
Labels: 👽 bug, ✨ FE
